### ISSUE TITLE
Problem with own customized data (or own file reference) within localization of tx_charts_domain_model_chartdata

### ISSUE THREAD

**Issue by ikonplant** [hoogi91/charts#548]
**Version(s) affected**: 2.0.6

- TYPO3 10.4
- PHP 7.4
- hoogi91/charts 2.0.6
- hoogi91/spreadsheets 3.3.1
- Languages: 0, 1
- All pages in connected mode

-------------

**Description**  

Translated Chart Dataset data (`tx_charts_domain_model_chartdata`) refers the spreadsheet configuration of the origin data record (from `sys_language_uid` 0). Changes, made for translated record via BE, are not stored in the database correctly and are not shown in BE correctly.

-------------

**How to reproduce**  

1. Upload Excel sheet to file storage
2. Create Chart Dataset, language 0
3. Make selection for spreadsheet_labels, spreadsheet_datasets, spreadsheet_datasets_labels in BE
4. Save
5. Translate chart dataset to language 1
6. Make (same or different) selection for spreadsheet_labels, spreadsheet_datasets, spreadsheet_datasets_labels in BE
7. Save

**Given / created Data:**

- Excel:
  - test_diagramm_daten_de.xlsx

- DB: sys_file_reference:
```
uid,pid,sys_language_uid,uid_local,uid_foreign,l10n_parent
662674,99484,0,200146,80,0
662675,99484,1,200146,85,662674
```

- DB: tx_charts_domain_model_chartdata:
```
uid,pid,l10n_parent,spreadsheet_labels,spreadsheet_datasets,spreadsheet_datasets_labels
80,99484,0,spreadsheet://662674?index=0&range=B1:C1&direction=horizontal,spreadsheet://662674?index=0&range=B2:C4&direction=horizontal,spreadsheet://662674?index=0&range=A2:A4&direction=vertical
85,99484,80,spreadsheet://662674?index=0&range=B1:C1&direction=horizontal,spreadsheet://662674?index=0&range=B2:C4&direction=horizontal,spreadsheet://662674?index=0&range=A2:A4&direction=vertical
```

- BE: translated Chart Dataset record (UID 85), Markup of the form for _Labels (single row or column)[spreadsheet_labels]_:
`<option value="662675">test_diagramm_daten_de</option>`

- But within spreadsheet_labels field of `tx_charts_domain_model_chartdata` UID **85** `sys_file_reference` **662674** is referenced: `spreadsheet://662674?index=0&range=B1:C1&direction=horizontal`,
Which also has an impact on frontend rendering, of course.

**Further use case to recheck the problem in frontend:**

Add second Excel sheet with the same data, but translated labels to the file storage
Set relation within translated Chart Dataset to the second Excel sheet

-------------

**Additional context**  

Language 0:
![chartsdata_language_0](https://github.com/user-attachments/assets/a8cc5783-5260-4245-ab85-fa4f73381c66)
Translated, language 1:
![chartsdata_language_1](https://github.com/user-attachments/assets/ff95c88f-ad81-429e-a7f7-fc949cf245cf)

**Comment by hoogi91** [comment]
Hey @ikonplant,

thanks for the detailed report. Indeed it looks like there is a missing data handler that selects the correct spreadsheet right after translating an entry.
I played already a bit around and I'm confident to find a good solution for it. I guess it will require a bugfix in https://github.com/hoogi91/spreadsheets too, but then this issue should disappear. Hope to create a release on the weekend :)

**Comment by hoogi91** [comment]
Hey @ikonplant,

this issue should be solved with either spreadsheets version [3.3.2](https://github.com/hoogi91/spreadsheets/releases/tag/3.3.2) or [4.0.2](https://github.com/hoogi91/spreadsheets/releases/tag/4.0.2).

Can you test this and write me some feedback?
Thanks

**Comment by ikonplant** [comment]
Hi @hoogi91 !
Thank you!
I will have a look at it tomorrow and give you my feedback.

**Comment by ikonplant** [comment]
Hi @hoogi91 !
Unfortunately the problem is not solved for our customer.
I will come back to you with detailed report.

**Comment by hoogi91** [comment]
@ikonplant did you check it again or was there any option how you solved it in the meantime for your customer? Would be nice to know if there is still a bug with localization of the datasets. In case there is an issue please reach me out to further check why it happens on your TYPO3 instance :)

**Comment by ikonplant** [comment]
@hoogi91 Thank's for pinging me. Right now I am not up to date, but I will recheck the status.

**Comment by ikonplant** [comment]
Hi @hoogi91!

Just rechecked on TYPO3 v12, charts 3.0.3, spreadsheets 4.0.3. 

The symptom from this issue, language 1 chartdata referencing the language 0 **sys_file_reference** after localization, is no longer reproducible. The data handler does its job, the **spreadsheet_*** fields on the localized record now point to the language 1 **sys_file_reference** after the localization. Thanks for fixing it.

One related but distinct case came up while testing (wrong relation => FE crash when the editor replaces the file in the localization record afterwards). I will file that as a separate issue.
